attributes:
    LastSwiftUpdateCheck: 1250
    LastUpgradeCheck: 1250
configs:
    Debug: debug
    Release: release
name: QuasiTwitter
options:
    bundleIdPrefix: com.justterror.QuasiTwitter
    defaultConfig: Release
    deploymentTarget:
        iOS: 15.0
    groupSortPosition: top
    minimumXcodeGenVersion: 2.25.0
    xcodeVersion: 13.0
settings:
    configs:
        Debug:
            CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
            MARKETING_VERSION: 1.0
            IPHONEOS_DEPLOYMENT_TARGET: 15.0
            MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
            MTL_FAST_MATH: YES
            SDKROOT: iphoneos
            SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
            SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
            CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
            MARKETING_VERSION: 1.0
            IPHONEOS_DEPLOYMENT_TARGET: 15.0
            MTL_FAST_MATH: YES
            SDKROOT: iphoneos
            SWIFT_COMPILATION_MODE: wholemodule
            SWIFT_OPTIMIZATION_LEVEL: -O
packages:
    Lottie:
        url: https://github.com/airbnb/lottie-ios
        from: 3.2.3
    Firebase:
        url: https://github.com/firebase/firebase-ios-sdk
        from: 8.0.0
    SnapKit:
        url: https://github.com/SnapKit/SnapKit
        from: 5.0.1

targets:
    QuasiTwitter:
        deploymentTarget: 15.0
        platform: iOS
        type: application
        scheme:
            testTargets:
                # tests here.
        prebuildScripts:
        - name: Swiftlint
          runOnlyWhenInstalling: false
          script: "if test -d \"/opt/homebrew/bin/\"; then\n  PATH=\"/opt/homebrew/bin/:${PATH}\"\nfi\n\nexport
            PATH\n\nif which swiftlint >/dev/null; then\n  swiftlint\nelse\n  echo \"warning:
            SwiftLint not installed, download from https://github.com/realm/SwiftLint\"\nfi\n"
          shell: /bin/sh
        settings:
            configs:
                Debug:
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
                    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
                    CODE_SIGN_IDENTITY: Apple Development
                    CODE_SIGN_STYLE: Automatic
                    CURRENT_PROJECT_VERSION: 1
                    INFOPLIST_FILE: QuasiTwitter/Info.plist
                    IPHONEOS_DEPLOYMENT_TARGET: 15.0
                    PRODUCT_BUNDLE_IDENTIFIER: com.justterror.QuasiTwitter
                    PRODUCT_NAME: "$(TARGET_NAME)"
                    PROVISIONING_PROFILE_SPECIFIER:
                    SWIFT_VERSION: 5.5
                    TARGETED_DEVICE_FAMILY: "1,2"
                    VERSIONING_SYSTEM: apple-generic
                Release:
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
                    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
                    CODE_SIGN_IDENTITY: Apple Development
                    CODE_SIGN_STYLE: Automatic
                    CURRENT_PROJECT_VERSION: 1
                    INFOPLIST_FILE: QuasiTwitter/Info.plist
                    IPHONEOS_DEPLOYMENT_TARGET: 15.0
                    PRODUCT_BUNDLE_IDENTIFIER: com.justterror.QuasiTwitter
                    PRODUCT_NAME: "$(TARGET_NAME)"
                    PROVISIONING_PROFILE_SPECIFIER:
                    SWIFT_VERSION: 5.5
                    TARGETED_DEVICE_FAMILY: "1,2"
                    VERSIONING_SYSTEM: apple-generic
        sources: [QuasiTwitter]
        dependencies:
          - package: Lottie
          - package: SnapKit
          - package: Firebase
            product: FirebaseAuth
          - package: Firebase
            product: FirebaseAnalytics
#          - package: Firebase
#            product: FirebaseStorage
#          - package: Firebase
#            product: FirebaseDatabase
